### ISSUE TITLE
Meta image is not correct

### ISSUE THREAD

**Issue by lifeng-yin** [RythmHacks/links.rythmhacks.ca#1]
The meta image is actually a preview image from [https://metatags.io](https://metatags.io) which is probably the generator that you used. It should be changed to something related to Rythmhacks, like a preview of the website.

<img width="519" alt="Screen Shot 2022-12-19 at 5 22 52 PM" src="https://user-images.githubusercontent.com/105888573/208538329-a238b223-3fac-4ff2-93e2-6db7dc66108b.png">

**Comment by jeffrey-zang** [comment]
i think it's a vercel thing, idk how to fix this

**Comment by jeffrey-zang** [comment]
make a pr if you want

**Comment by lifeng-yin** [comment]
alright on it

**Comment by lifeng-yin** [comment]
Ok, it's fixed somehow. I might change to the image to make it look more appealing in the future.
