### ISSUE TITLE
chore: update the metadata to match rythmhacks.ca

### ISSUE THREAD

**Issue by jeffrey-zang** [RythmHacks/links.rythmhacks.ca#3]
Previewed on discord
![image](https://user-images.githubusercontent.com/66485719/233876736-b81258ed-9a95-440c-9b6e-8b9f580837eb.png)
vs
![image](https://user-images.githubusercontent.com/66485719/233876743-7b459890-93d9-4bc1-bc0d-cd6caaa10fc2.png)

@lifeng-yin you can probably just copy the metadata over

**Comment by lifeng-yin** [comment]
Alright, will copy it.

**Comment by lifeng-yin** [comment]
Copied everything except for the title.

**Comment by lifeng-yin** [comment]
Looks like the banner.png isn't working, trying to fix right now.

**Comment by lifeng-yin** [comment]
Closed as the banner.png works and displays properly now.
